config/routes.rb
Rails.application.routes.draw do

  resources :compras
  resources :prestadors
  resources :servicos
  get '/clientes/aniversariantes', to: 'clientes#aniversariantes'
  get '/clientes/contratos', to: 'clientes#contratos'
  resources :enderecos
  resources :clientes

  get 'signup', to: 'users#new'
  resources :users, except: [:new]


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/cliente.rb
class Cliente < ApplicationRecord
  has_one :endereco, dependent: :destroy

  # scope :aniversariante_mes, -> { where(nascimento: "1984-08-05"
  #
  #   ) }
  #scope :aniversariante_mes, -> { where("month(nascimento) = ?", Time.now.month) }
  #scope :aniversariante_mes, -> { where("nascimento.strftime('%m') = ?", Time.now.month) }
  scope :aniversariante_mes, -> { where("strftime('%m', nascimento) = ?", Time.now.strftime('%m')) }

  def mes_nascimento
    nascimento.strftime("%m")
  end

  def mes_corrente
    Date.today.strftime("%m")
  end

end

app/controllers/clientes_controller.rb
class ClientesController < ApplicationController
  before_action :set_cliente, only: [:show, :edit, :update, :destroy]

  # GET /clientes
  # GET /clientes.json
  def index
    @clientes = Cliente.all
  end

  def aniversariantes
    @clientes = Cliente.aniversariante_mes
  end

  def contratos
    @clientes = Cliente.all
  end

  # GET /clientes/1
  # GET /clientes/1.json
  def show
  end

  # GET /clientes/new
  def new
    @cliente = Cliente.new
  end

  # GET /clientes/1/edit
  def edit
  end

  # POST /clientes
  # POST /clientes.json
  def create
    @cliente = Cliente.new(cliente_params)

    respond_to do |format|
      if @cliente.save
        format.html { redirect_to :controller => 'enderecos', :action => 'new'}
        format.json { render :show, status: :created, location: @cliente }
      else
        format.html { render :new }
        format.json { render json: @cliente.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /clientes/1
  # PATCH/PUT /clientes/1.json
  def update
    respond_to do |format|
      if @cliente.update(cliente_params)
        format.html { redirect_to @cliente, notice: 'Cliente was successfully updated.' }
        format.json { render :show, status: :ok, location: @cliente }
      else
        format.html { render :edit }
        format.json { render json: @cliente.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /clientes/1
  # DELETE /clientes/1.json
  def destroy
    @cliente.destroy
    respond_to do |format|
      format.html { redirect_to clientes_url, notice: 'Cliente was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cliente
      @cliente = Cliente.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cliente_params
      params.require(:cliente).permit(:nome, :cpf, :rg, :nascimento, :email, :telefone, :obs)
    end
end

app/helpers/clientes_helper.rb
module ClientesHelper
end

app/views/clientes/_form.html.erb
<%= form_with(model: cliente, local: true) do |form| %>
  <% if cliente.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(cliente.errors.count, "error") %> prohibited this cliente from being saved:</h2>

      <ul>
      <% cliente.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :nome %>
    <%= form.text_field :nome, id: :cliente_nome %>
  </div>

  <div class="field">
    <%= form.label :cpf %>
    <%= form.text_field :cpf, id: :cliente_cpf %>
  </div>

  <div class="field">
    <%= form.label :rg %>
    <%= form.text_field :rg, id: :cliente_rg %>
  </div>

  <div class="field">
    <%= form.label :nascimento %>
    <%= form.date_select :nascimento, id: :cliente_nascimento, :start_year=>1930,:end_year=>2030 %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email, id: :cliente_email %>
  </div>

  <div class="field">
    <%= form.label :telefone %>
    <%= form.text_field :telefone, id: :cliente_telefone %>
  </div>

  <div class="field">
    <%= form.label :obs %>
    <%= form.text_area :obs, id: :cliente_obs %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/clientes/aniversariantes.html.erb
<p id="notice"><%= notice %></p>

<h1>Aniversariantes do Mês</h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Nome</th>
      <th>Cpf</th>
      <th>Rg</th>
      <th>Nascimento</th>
      <th>Email</th>
      <th>Telefone</th>
      <th>Obs</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @clientes.each do |cliente| %>
      <tr>
        <td><%= cliente.nome %></td>
        <td><%= cliente.cpf %></td>
        <td><%= cliente.rg %></td>
        <td><%= cliente.nascimento %></td>
        <td><%= cliente.email %></td>
        <td><%= cliente.telefone %></td>
        <td><%= cliente.obs %></td>
        <td><%= link_to 'Show', cliente %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Cliente', new_cliente_path %>

app/views/clientes/contratos.html.erb
<p id="notice"><%= notice %></p>

<h1>Aniversariantes do Mês</h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Nome</th>
      <th>Cpf</th>
      <th>Rg</th>
      <th>Nascimento</th>
      <th>Email</th>
      <th>Telefone</th>
      <th>Obs</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @clientes.each do |cliente| %>
      <tr>
        <td><%= cliente.nome %></td>
        <td><%= cliente.cpf %></td>
        <td><%= cliente.rg %></td>
        <td><%= cliente.nascimento %></td>
        <td><%= cliente.email %></td>
        <td><%= cliente.telefone %></td>
        <td><%= cliente.obs %></td>
        <td><%= link_to 'Show', cliente %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Cliente', new_cliente_path %>

app/views/clientes/edit.html.erb
<h1>Editing Cliente</h1>

<%= render 'form', cliente: @cliente %>

<%= link_to 'Show', @cliente %> |
<%= link_to 'Ver endereco', @cliente.endereco %> |
<%= link_to 'Back', clientes_path %>

app/views/clientes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Clientes</h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Nome</th>
      <th>Cpf</th>
      <th>Rg</th>
      <th>Nascimento</th>
      <th>Email</th>
      <th>Telefone</th>
      <th>Obs</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @clientes.each do |cliente| %>
      <tr>
        <td><%= cliente.nome %></td>
        <td><%= cliente.cpf %></td>
        <td><%= cliente.rg %></td>
        <td><%= cliente.nascimento %></td>
        <td><%= cliente.email %></td>
        <td><%= cliente.telefone %></td>
        <td><%= cliente.obs %></td>
        <td><%= link_to 'Show', cliente %></td>
        <td><%= link_to 'Edit', edit_cliente_path(cliente) %></td>
        <td><%= link_to 'Destroy', cliente, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Cliente', new_cliente_path %>

app/views/clientes/new.html.erb
<h1>New Cliente</h1>

<%= render 'form', cliente: @cliente %>

<%= link_to 'Back', clientes_path %>

app/views/clientes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nome:</strong>
  <%= @cliente.nome %>
</p>

<p>
  <strong>Cpf:</strong>
  <%= @cliente.cpf %>
</p>

<p>
  <strong>Rg:</strong>
  <%= @cliente.rg %>
</p>

<p>
  <strong>Nascimento:</strong>
  <%= @cliente.nascimento %>
</p>

<p>
  <strong>Email:</strong>
  <%= @cliente.email %>
</p>

<p>
  <strong>Telefone:</strong>
  <%= @cliente.telefone %>
</p>

<p>
  <strong>Obs:</strong>
  <%= @cliente.obs %>
</p>

<br>
<%= link_to 'Edit', edit_cliente_path(@cliente) %> |
<%= link_to 'Back', clientes_path %>


<p>
  <strong>Logradouro:</strong>
  <%= @cliente.endereco.logradouro %>
</p>

<p>
  <strong>Numero:</strong>
  <%= @cliente.endereco.numero %>
</p>

<p>
  <strong>Bairro:</strong>
  <%= @cliente.endereco.bairro %>
</p>

<p>
  <strong>Complemento:</strong>
  <%= @cliente.endereco.complemento %>
</p>

<p>
  <strong>Cidade:</strong>
  <%= @cliente.endereco.cidade %>
</p>

<p>
  <strong>Estado:</strong>
  <%= @cliente.endereco.estado %>
</p>
<%= link_to 'Edit', edit_endereco_path(@cliente.endereco) %> |