config/routes.rb
Rails.application.routes.draw do

  resources :compras
  resources :prestadors
  resources :servicos
  get '/clientes/aniversariantes', to: 'clientes#aniversariantes'
  get '/clientes/contratos', to: 'clientes#contratos'
  resources :enderecos
  resources :clientes

  get 'signup', to: 'users#new'
  resources :users, except: [:new]


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/endereco.rb
class Endereco < ApplicationRecord
  belongs_to :cliente
end

app/controllers/enderecos_controller.rb
class EnderecosController < ApplicationController
  before_action :set_endereco, only: [:show, :edit, :update, :destroy]

  # GET /enderecos
  # GET /enderecos.json
  def index
    @enderecos = Endereco.all
  end

  # GET /enderecos/1
  # GET /enderecos/1.json
  def show
  end

  # GET /enderecos/new
  def new
    @endereco = Endereco.new
  end

  # GET /enderecos/1/edit
  def edit
  end

  # POST /enderecos
  # POST /enderecos.json
  def create
    @endereco = Endereco.new(endereco_params)
    @endereco.cliente = Cliente.last

    respond_to do |format|
      if @endereco.save
        format.html { redirect_to @endereco.cliente, notice: 'Endereco was successfully created.' }
        format.json { render :show, status: :created, location: @endereco }
      else
        format.html { render :new }
        format.json { render json: @endereco.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /enderecos/1
  # PATCH/PUT /enderecos/1.json
  def update
    respond_to do |format|
      if @endereco.update(endereco_params)
        format.html { redirect_to @endereco, notice: 'Endereco was successfully updated.' }
        format.json { render :show, status: :ok, location: @endereco }
      else
        format.html { render :edit }
        format.json { render json: @endereco.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /enderecos/1
  # DELETE /enderecos/1.json
  def destroy
    @endereco.destroy
    respond_to do |format|
      format.html { redirect_to enderecos_url, notice: 'Endereco was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_endereco
      @endereco = Endereco.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def endereco_params
      params.require(:endereco).permit(:logradouro, :numero, :bairro, :complemento, :cidade, :estado)
    end
end

app/helpers/enderecos_helper.rb
module EnderecosHelper
end

app/views/enderecos/_form.html.erb
<%= form_with(model: endereco, local: true) do |form| %>
  <% if endereco.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(endereco.errors.count, "error") %> prohibited this endereco from being saved:</h2>

      <ul>
      <% endereco.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :logradouro %>
    <%= form.text_field :logradouro, id: :endereco_logradouro %>
  </div>

  <div class="field">
    <%= form.label :numero %>
    <%= form.text_field :numero, id: :endereco_numero %>
  </div>

  <div class="field">
    <%= form.label :bairro %>
    <%= form.text_field :bairro, id: :endereco_bairro %>
  </div>

  <div class="field">
    <%= form.label :complemento %>
    <%= form.text_field :complemento, id: :endereco_complemento %>
  </div>

  <div class="field">
    <%= form.label :cidade %>
    <%= form.text_field :cidade, id: :endereco_cidade %>
  </div>

  <div class="field">
    <%= form.label :estado %>
    <%= form.text_field :estado, id: :endereco_estado %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>


<% end %>

app/views/enderecos/edit.html.erb
<h1>Editing Endereco</h1>

<%= render 'form', endereco: @endereco %>

<%= link_to 'Show', @endereco %> |
<%= link_to 'Back', enderecos_path %>

app/views/enderecos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Enderecos</h1>

<table>
  <thead>
    <tr>
      <th>Cliente</th>
      <th>Logradouro</th>
      <th>Numero</th>
      <th>Bairro</th>
      <th>Complemento</th>
      <th>Cidade</th>
      <th>Estado</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @enderecos.each do |endereco| %>
      <tr>
        <td><%= endereco.cliente.nome %></td>
        <td><%= endereco.logradouro %></td>
        <td><%= endereco.numero %></td>
        <td><%= endereco.bairro %></td>
        <td><%= endereco.complemento %></td>
        <td><%= endereco.cidade %></td>
        <td><%= endereco.estado %></td>
        <td><%= link_to 'Show', endereco %></td>
        <td><%= link_to 'Edit', edit_endereco_path(endereco) %></td>
        <td><%= link_to 'Destroy', endereco, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Endereco', new_endereco_path %>

app/views/enderecos/new.html.erb
<h1>New Endereco</h1>

<%= render 'form', endereco: @endereco %>

<%= link_to 'Back', enderecos_path %>

app/views/enderecos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Cliente:</strong>
  <%= @endereco.cliente.nome %>
</p>

<p>
  <strong>Logradouro:</strong>
  <%= @endereco.logradouro %>
</p>

<p>
  <strong>Numero:</strong>
  <%= @endereco.numero %>
</p>

<p>
  <strong>Bairro:</strong>
  <%= @endereco.bairro %>
</p>

<p>
  <strong>Complemento:</strong>
  <%= @endereco.complemento %>
</p>

<p>
  <strong>Cidade:</strong>
  <%= @endereco.cidade %>
</p>

<p>
  <strong>Estado:</strong>
  <%= @endereco.estado %>
</p>

<%= link_to 'Edit', edit_endereco_path(@endereco) %> |
<%= link_to 'Back', enderecos_path %>