config/routes.rb
Rails.application.routes.draw do

  resources :compras
  resources :prestadors
  resources :servicos
  get '/clientes/aniversariantes', to: 'clientes#aniversariantes'
  get '/clientes/contratos', to: 'clientes#contratos'
  resources :enderecos
  resources :clientes

  get 'signup', to: 'users#new'
  resources :users, except: [:new]


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/prestador.rb
class Prestador < ApplicationRecord
end

app/controllers/prestadors_controller.rb
class PrestadorsController < ApplicationController
  before_action :set_prestador, only: [:show, :edit, :update, :destroy]

  # GET /prestadors
  # GET /prestadors.json
  def index
    @prestadors = Prestador.all
  end

  # GET /prestadors/1
  # GET /prestadors/1.json
  def show
  end

  # GET /prestadors/new
  def new
    @prestador = Prestador.new
  end

  # GET /prestadors/1/edit
  def edit
  end

  # POST /prestadors
  # POST /prestadors.json
  def create
    @prestador = Prestador.new(prestador_params)

    respond_to do |format|
      if @prestador.save
        format.html { redirect_to @prestador, notice: 'Prestador was successfully created.' }
        format.json { render :show, status: :created, location: @prestador }
      else
        format.html { render :new }
        format.json { render json: @prestador.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /prestadors/1
  # PATCH/PUT /prestadors/1.json
  def update
    respond_to do |format|
      if @prestador.update(prestador_params)
        format.html { redirect_to @prestador, notice: 'Prestador was successfully updated.' }
        format.json { render :show, status: :ok, location: @prestador }
      else
        format.html { render :edit }
        format.json { render json: @prestador.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /prestadors/1
  # DELETE /prestadors/1.json
  def destroy
    @prestador.destroy
    respond_to do |format|
      format.html { redirect_to prestadors_url, notice: 'Prestador was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_prestador
      @prestador = Prestador.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def prestador_params
      params.require(:prestador).permit(:nome, :email, :telefone, :cnpj, :cpf, :rua, :bairro, :numero, :cidade, :dadosBancarios)
    end
end

app/helpers/prestadors_helper.rb
module PrestadorsHelper
end

app/views/prestadors/_form.html.erb
<%= form_with(model: prestador, local: true) do |form| %>
  <% if prestador.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(prestador.errors.count, "error") %> prohibited this prestador from being saved:</h2>

      <ul>
      <% prestador.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :nome %>
    <%= form.text_field :nome, id: :prestador_nome %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email, id: :prestador_email %>
  </div>

  <div class="field">
    <%= form.label :telefone %>
    <%= form.text_field :telefone, id: :prestador_telefone %>
  </div>

  <div class="field">
    <%= form.label :cnpj %>
    <%= form.text_field :cnpj, id: :prestador_cnpj %>
  </div>

  <div class="field">
    <%= form.label :cpf %>
    <%= form.text_field :cpf, id: :prestador_cpf %>
  </div>

  <div class="field">
    <%= form.label :rua %>
    <%= form.text_field :rua, id: :prestador_rua %>
  </div>

  <div class="field">
    <%= form.label :bairro %>
    <%= form.text_field :bairro, id: :prestador_bairro %>
  </div>

  <div class="field">
    <%= form.label :numero %>
    <%= form.text_field :numero, id: :prestador_numero %>
  </div>

  <div class="field">
    <%= form.label :cidade %>
    <%= form.text_field :cidade, id: :prestador_cidade %>
  </div>

  <div class="field">
    <%= form.label :dadosBancarios %>
    <%= form.text_field :dadosBancarios, id: :prestador_dadosBancarios %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/prestadors/edit.html.erb
<h1>Editing Prestador</h1>

<%= render 'form', prestador: @prestador %>

<%= link_to 'Show', @prestador %> |
<%= link_to 'Back', prestadors_path %>

app/views/prestadors/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Prestadors</h1>

<table>
  <thead>
    <tr>
      <th>Nome</th>
      <th>Email</th>
      <th>Telefone</th>
      <th>Cnpj</th>
      <th>Cpf</th>
      <th>Rua</th>
      <th>Bairro</th>
      <th>Numero</th>
      <th>Cidade</th>
      <th>Dadosbancarios</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @prestadors.each do |prestador| %>
      <tr>
        <td><%= prestador.nome %></td>
        <td><%= prestador.email %></td>
        <td><%= prestador.telefone %></td>
        <td><%= prestador.cnpj %></td>
        <td><%= prestador.cpf %></td>
        <td><%= prestador.rua %></td>
        <td><%= prestador.bairro %></td>
        <td><%= prestador.numero %></td>
        <td><%= prestador.cidade %></td>
        <td><%= prestador.dadosBancarios %></td>
        <td><%= link_to 'Show', prestador %></td>
        <td><%= link_to 'Edit', edit_prestador_path(prestador) %></td>
        <td><%= link_to 'Destroy', prestador, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Prestador', new_prestador_path %>

app/views/prestadors/new.html.erb
<h1>New Prestador</h1>

<%= render 'form', prestador: @prestador %>

<%= link_to 'Back', prestadors_path %>

app/views/prestadors/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nome:</strong>
  <%= @prestador.nome %>
</p>

<p>
  <strong>Email:</strong>
  <%= @prestador.email %>
</p>

<p>
  <strong>Telefone:</strong>
  <%= @prestador.telefone %>
</p>

<p>
  <strong>Cnpj:</strong>
  <%= @prestador.cnpj %>
</p>

<p>
  <strong>Cpf:</strong>
  <%= @prestador.cpf %>
</p>

<p>
  <strong>Rua:</strong>
  <%= @prestador.rua %>
</p>

<p>
  <strong>Bairro:</strong>
  <%= @prestador.bairro %>
</p>

<p>
  <strong>Numero:</strong>
  <%= @prestador.numero %>
</p>

<p>
  <strong>Cidade:</strong>
  <%= @prestador.cidade %>
</p>

<p>
  <strong>Dadosbancarios:</strong>
  <%= @prestador.dadosBancarios %>
</p>

<%= link_to 'Edit', edit_prestador_path(@prestador) %> |
<%= link_to 'Back', prestadors_path %>