config/routes.rb
Rails.application.routes.draw do

  resources :compras
  resources :prestadors
  resources :servicos
  get '/clientes/aniversariantes', to: 'clientes#aniversariantes'
  get '/clientes/contratos', to: 'clientes#contratos'
  resources :enderecos
  resources :clientes

  get 'signup', to: 'users#new'
  resources :users, except: [:new]


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <!-- <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button> -->
      <a class="navbar-brand" href="#" ><%= image_tag("logo.png", size: "150x120", class: "img-responsive") %></a>

    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <!-- <li class="active"><a href="#">Link <span class="sr-only">(current)</span></a></li>
        <li><a href="#">Link</a></li> -->
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Cliente <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><%=link_to "Cadastrar", new_cliente_path %></li>
            <li><%=link_to "Consultar", clientes_path %></li>
            <li><%=link_to "Aniversariantes", clientes_aniversariantes_path %></li>
            <li role="separator" class="divider"></li>
            <li><%=link_to "Contratos", clientes_contratos_path %></li>
          </ul>
        </li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Serviço <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><%=link_to "Cadastrar", new_servico_path %></li>
            <li><%=link_to "Consultar", servicos_path %></li>
          </ul>
        </li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Terceiros <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><%=link_to "Cadastrar prestador", new_prestador_path %></li>
            <li><%=link_to "Consultar prestador", prestadors_path %></li>
            <li role="separator" class="divider"></li>
            <li><%=link_to "Cadastrar serviço", new_cliente_path %></li>
            <li><%=link_to "Consultar serviço", clientes_path %></li>
          </ul>
        </li>
        
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Compras <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><%=link_to "Cadastrar", new_compra_path %></li>
            <li><%=link_to "Consultar", compras_path %></li>
          </ul>
        </li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Financeiro <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><%=link_to "Cadastrar", new_cliente_path %></li>
            <li><%=link_to "Consultar", clientes_path %></li>
            <li><%=link_to "Aniversariantes", clientes_aniversariantes_path %></li>
            <li role="separator" class="divider"></li>
            <li><%=link_to "Contratos", clientes_contratos_path %></li>
          </ul>
        </li>
      </ul>
      <!-- <form class="navbar-form navbar-left">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form> -->
      <ul class="nav navbar-nav navbar-right">
        <li><a href="#">Link</a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Separated link</a></li>
          </ul>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NathaliaAmaralRails</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <%= render "layouts/navbar"%>
  <body>
    <div class="container">
      <%= yield %>
    </div>
    <br>
    <div class="container">
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>